# Site settings
title: Michael Gaudreau's Resume
description: A web designed Resume for Michael Gaudreau
favicon: https://photos.app.goo.gl/6y6gJbXZw2s1UrHMA
# favicon: /assets/img/avatar.JPG
# baseurl: https://ddbullfrog.github.io/resumecard
# url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Copyright Year
copyright:
  year: 2020

# Author settings
author:
  name: Michael Gaudreau
  title: Software Developer
  address: Hartford, Connecticut
  email: dongg.liang#gmail.com
  link: http://ddbullfrog.com
  weibo:
  github: mikeg1440
  linkedin: michael-gaudreau
  twitter: MyLogicBytes1
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Staples
      location: Glastonbury, Connecticut
      title: Team Supervisor
      started: 2016
      duration: (2016 - Present)
      description: Responsible for training associates on technical skills including data backups/transfers, part replacements/installations, operating system installations, as well as customer service best practices.  Recognized by the Office of the President for providing a customer centric environment and developing customer relationships.  Assist at locations with poor metrics in renovations/ planogram refreshes to improve sales and overall customer satisfaction.  Responsible for ensuring associates have offered applicable services and identified customer needs when giving access to high ticket items in lock up to drive maximum profitability.  Perform quality checking for Copy & Print production jobs to ensure customer satisfaction.  Generate leads for large production jobs for businesses.  Perform inventory management to ensure product is stocked and correctly accounted.  Manage departments associates when acting as Manager on Duty to direct associates toward company objectives.

    - work2:
      company: Freelance
      location: Shanghai, China
      title: Handyman/Home Improvement
      started: 2014
      duration: (2014 - 2016)
      description: Determined required services/labor/supplies for job bids.  Performed repair & maintenance of interior facilities (bathroom, kitchen, floor/carpet installations).  Sourced and hired contractors for larger projects that required permits or licensing, working closely with contractors to meet goals for timelines and budget constraints.  Assisted with installation of appliances and proper disposal of old units.  Performed general maintenance tasks and repairs to keep appliances and facilities in working order.

    - work3:
      company: CVS
      location: Glastonbury, CT
      title: Photolab Supervisor
      started: 2010
      duration: (2010 - 2014)
      description: Coordinated and trained associates in photo lab equipment, kiosks and related technologies maintenance tasks.  Developed film and performed required equipment tests to ensure quality of photo production.  Developed close relationships with customers to drive customer satisfaction.  Ensured all Photo Lab employees comply with Federal and State laws and OSHA regulations.  Trained associates and ensured proper disposal of hazardous wastes to maintain a safe environment.  Assisted customers in all non-pharmaceutical areas of the store to ensure customer satisfaction.  Performed inventory counts and price changes to ensure products were in stock and rotated according to expiration.  Managed products and upheld proper facing/display of products to drive sales in addition to photo lab duties.

  educationHistory:
    - education1:
      organization: Flatiron School
      location: Online
      degree: Software Engineering Diploma
      major: Full Stack Development
      started: 2019
      duration: (2019 - 2020)
      description: 'A immersive course that launches students into fulfilling careers as software engineers, data scientists, and UX/UI designers through rigorous, market-aligned curricula, and the support of seasoned instructors and personal career coaches. Through test-driven labs and portfolio projects, Flatiron teaches students to think and build like software engineers and data scientists. Flatiron School’s UX/UI Design Immersive includes a client project to give students client-facing experience and an industry-vetted portfolio.  Rated #1 on Course Reports Best 48 Coding Bootcamps in 2019.'

    - education2:
      organization: Manchester Community College
      location: Manchester, CT
      degree: Bachlor Candidate
      major: Computer Science
      started: 2018
      duration: (2018 - Present)
      description: Named in the Presidents List in recognition of academic performance, attending part-time while working at Staples.  MCC is a rigorous calculus-based program designed to prepare students for transfer to Connecticut state institutions granting bachelor’s degrees.  Planning on attending Central Connecticut State University for the completion of my Bachlors in Computer Science.

  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
  skills:
    - JavaScript
    - HTML
    - CSS
    - Node.js
    - Ruby
    - Ruby on Rails
    - Docker
    - Virtualbox
    - Vagrant
    - Linux
    - Microsoft Office Suite
    - Photoshop
    - Python
    - Java
  technicalProjects:
    - project1:
      name: Invoicer
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - project2:
      name: Todo App
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - project3:
      name: Moniez
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - project4:
      name: Freelancer
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
